# Generated by Django 4.1.2 on 2022-10-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='the_name',
        ),
    ]
